# Generated by Django 3.0.8 on 2020-08-15 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0002_agency_eligibility'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('responses', models.BooleanField(default=False, help_text='Grants access to responses created by any of the agencies within the security group', verbose_name='Access Responses')),
                ('enrollments', models.BooleanField(default=False, verbose_name='Access Client enrollment data')),
                ('referrals', models.BooleanField(default=False, verbose_name='Access Client referral data')),
                ('agencies', models.ManyToManyField(related_name='security_groups', to='agency.Agency')),
                ('programs', models.ManyToManyField(related_name='security_groups', to='program.Program')),
            ],
            options={
                'db_table': 'security_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityGroupUserAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=125, null=True)),
                ('agency_ref', models.ForeignKey(db_column='agency_ref', null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.Agency', to_field='ref_id')),
                ('group_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_group_user_agency',
            },
        ),
        migrations.CreateModel(
            name='SecurityGroupAgencyConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency')),
                ('security_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.SecurityGroup')),
            ],
            options={
                'db_table': 'security_group_agency_config',
            },
        ),
    ]
