# Generated by Django 3.0.8 on 2020-07-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20200707_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_removed',
        ),
    ]
