# Generated by Django 3.0.8 on 2020-08-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmatching',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching', to='program.Program'),
        ),
    ]
