# Generated by Django 3.0.7 on 2020-07-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20200623_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmatching',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='clientmatchinghistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='clientmatchingnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='matchingconfig',
            options={'ordering': ['-created_at']},
        ),
    ]
