# Generated by Django 3.0.7 on 2020-07-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_auto_20200709_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmatching',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='clientmatching',
            name='step',
        ),
    ]
