# Generated by Django 3.0.8 on 2020-07-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_auto_20200713_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmatching',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='matchingconfig',
            name='is_removed',
        ),
    ]
