# Generated by Django 3.0.7 on 2020-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0002_auto_20200707_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteligibility',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclienteligibility',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
