# Generated by Django 3.0.8 on 2020-08-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        ('eligibility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='eligibility',
            field=models.ManyToManyField(related_name='eligibility', through='eligibility.AgencyEligibilityConfig', to='eligibility.Eligibility'),
        ),
    ]
