# Generated by Django 3.0.7 on 2020-06-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('agency', '0004_auto_20200610_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='programs',
            field=models.ManyToManyField(to='program.Program'),
        ),
    ]
