# Generated by Django 3.0.7 on 2020-06-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20200617_1350'),
        ('agency', '0004_auto_20200610_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='programs',
            field=models.ManyToManyField(through='program.AgencyProgramConfig', to='program.Program'),
        ),
    ]
