# Generated by Django 3.0.7 on 2020-07-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0001_initial'),
        ('agency', '0006_auto_20200617_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='eligibility',
            field=models.ManyToManyField(related_name='eligibility', through='eligibility.AgencyEligibilityConfig', to='eligibility.Eligibility'),
        ),
    ]
