# Generated by Django 3.0.7 on 2020-07-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_agency_eligibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Agencies'},
        ),
    ]
