# Generated by Django 3.0.7 on 2020-07-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_auto_20200707_0933'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='security_groups',
            field=models.ManyToManyField(related_name='agencies', through='security.SecurityGroupAgencyConfig', to='security.SecurityGroup'),
        ),
    ]
