# Generated by Django 3.0.7 on 2020-07-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_agency_security_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['name'], 'verbose_name_plural': 'Agencies'},
        ),
        migrations.RemoveField(
            model_name='agency',
            name='security_groups',
        ),
    ]
