# Generated by Django 3.0.7 on 2020-06-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eligibility',
            options={'verbose_name_plural': 'Eligibility'},
        ),
    ]
