# Generated by Django 3.0.7 on 2020-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_auto_20200707_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
