# Generated by Django 3.0.6 on 2020-06-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200521_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(blank=True, to='survey.Question'),
        ),
    ]
