# Generated by Django 3.0.8 on 2020-07-20 14:56

import core.json_yaml_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20200717_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='columns',
            field=core.json_yaml_field.JsonYamlField(blank=True, null=True),
        ),
    ]
